### Obtener todos los contenidos
GET http://localhost:3001/contenidos

### Obtener un contenido por ID (id)
GET http://localhost:3001/contenidos/108
Content-Type: application/json

### Filtrar contenidos
GET http://localhost:3001/contenidos/filtrar?titulo=Westworld&gen=ciencia&ficcion&categoria=serie

### Agregar un nuevo contenido
POST http://localhost:3001/contenidos/agregar
Content-Type: application/json

{
      "titulo": "Undisputed",
      "gen": "Accion",
      "poster": "https://undisputed-2002.com/poster.jpg",
      "duracion": 96,
      "id_categoria": 2,
      "trailer": "https://www.youtube.com/watch?v=Diy3fuwhxQw",
      "temporadas": "N/A",
      "resumen": "George 'Iceman' Chambers (Ving Rhames) es un boxeador de peso pesado que es enviado a la prisión (récord de 46 victorias y 1 empate), por ser acusado de violación. A su llegada a la prisión, él oye hablar de Monroe Hutchen (Wesley Snipes), que en la prisión es clasificado como el campeón de boxeo (con un récord de 68 victorias y 0 derrotas). Cuando están ambos en el comedor, Iceman le pregunta curioso sobre sus habilidades en el boxeo y Monroe reconoce que es campeón de todas las categorías y pesos (mientras que Chambers sólo es campeón de los pesos pesados), después de averiguar que Monroe también ha sido campeón durante diez años seguidos (el tiempo que ha estado en la cárcel) procede a burlarse de él dándole una bofetada (Monroe se la devuelve dándole un rápido puñetazo en el pecho)."
}

### Actualizar un contenido
PATCH  http://localhost:3001/contenidos/actualizar/108
Content-Type: application/json

{
    "gen": "Terror",
    "duracion": 107
}

### Eliminar un contenido
DELETE http://localhost:3001/contenidos/eliminar/108
