### Obtener todos los contenidos
GET http://localhost:3001/contenidos

### Obtener un contenido por ID (id)
GET http://localhost:3001/contenidos/108
Content-Type: application/json

### Filtrar contenidos
GET http://localhost:3001/contenidos/filtrar?titulo=Westworld&gen=ciencia&ficcion&categoria=serie

### Agregar un nuevo contenido
POST http://localhost:3001/contenidos/agregar
Content-Type: application/json

{
      "titulo": "The Batman",
      "gen": "Accion",
      "poster": "https://the-batman.com/poster.jpg",
      "duracion": 130,
      "id_categoria": 2,
      "trailer": "https://www.youtube.com/watch?v=FUP3P9_mqvA&t=5s",
      "temporadas": "N/A",
      "resumen": "The Batman (Batman en Hispanoamérica) es una película estadounidense de superhéroes dirigida por Matt Reeves y basada en el personaje homónimo creado por Bob Kane y Bill Finger para DC Comics. El guion fue escrito por Reeves y Peter Craig, y narra los acontecimientos del vigilante Batman durante su segundo año luchando contra el crimen y la corrupción en Gotham City, además de enfrentarse al asesino serial Riddler. La cinta está protagonizada por Robert Pattinson como el personaje titular, acompañado de un elenco que incluye a Zoë Kravitz, Paul Dano, Jeffrey Wright, John Turturro, Peter Sarsgaard, Andy Serkis y Colin Farrell."
}

### Actualizar un contenido
PATCH  http://localhost:3001/contenidos/actualizar/109
Content-Type: application/json

{
    "gen": "Terror",
    "duracion": 107
}

### Eliminar un contenido
DELETE http://localhost:3001/contenidos/eliminar/108
